alias aliasloc='/home/dennis/.bash_aliases'
alias addgpl='wget -q http://www.gnu.org/licenses/gpl.txt -O LICENSE'
alias addcrapl='wget -q http://matt.might.net/articles/crapl/CRAPL-LICENSE.txt -O LICENSE'
alias bbc='ssh 192.168.1.2'
alias clr='echo "BAD DENNIS! Use ctrl+L"'
alias cls='clear; ls'
alias distro='cat /etc/*-release'
alias grep='grep --color=auto'
alias ins='sudo apt-get install'
alias install='sudo apt-get install'
alias ipconfig='ifconfig'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias ls='ls --color=auto'
alias lsg='ls | grep'
alias lsp='ls -1 /var/log/packages/ > package-list'
alias na='nano -c'
alias nano='nano -c'
alias sandcastle='ssh di07ty@sandcastle.cosc.brocku.ca'
alias sano='sudo nano'
alias t60='ssh dennis@192.168.1.102' #NOTE: only works on local network! - ip not static, changes often
alias tarbz2='tar -jxvf'
alias targz='tar -zxvf'
alias temp='sensors 2>/dev/null'
alias thoughtstack='java -jar ThoughtStack.jar'
alias upd='sudo apt-get update'
alias update='sudo apt-get update'
alias upg='sudo apt-get upgrade'
alias upgrade='sudo apt-get upgrade'
alias web='links -g -download-dir ~/ www.google.com'
alias execbin='chmod +x'
alias bookmarks='nano /home/dennis/.gtk-bookmarks'
alias xmleditor='cd /opt/bin/; ./serna-free-4.2'
alias md5='md5sum'
alias cman='man 3'
alias lsd='ls -d */' # List only directories in current directory.
alias disk='df -hT' # Disk space + file system type.
alias ram='free -m' # RAM usage in MB.
alias javadecompiler='/home/dennis/Downloads/jd-gui'
alias t='python ~/.t/t.py --task-dir ~/tasks --list tasks'
alias updatesite='scp index.html di07ty@sandcastle.cosc.brocku.ca:public_html/'
alias pngcrush='pngcrush -rem alla -reduce -brute'
alias mac='ifconfig | grep HWaddr'
alias mencoder='-oac mp3lame -ovc lavc' # e.g.) mencoder video.ogg -o output.avi
alias minecraft='java -Xmx1024M -Xms512M -cp Downloads/minecraft.jar net.minecraft.LauncherFrame'
alias size='du -ch | grep total'  # Total size of the current directory (human readable)
alias rep='sudo add-apt-repository'  # Add a new PPA to the repository
alias units='units --verbose'
alias pinknoise='play -t sl -r48000 -c2 - synth -1 pinknoise tremolo .1 40 <  /dev/zero'
alias whitenoise='cat /dev/urandom | aplay -f cd'
alias snipe='ps -x | grep' # Snipe an unresponsive process to get its pid to kill it.
alias serve='python -m SimpleHTTPServer' # Serve directory on local network, port 8000.
alias broadcast='script -qf | tee >(nc -l -p 5000) >(nc -l -p 5001) >(nc -l -p 5002)' # View with 'nc ipaddr port'.
alias pushd='pushd >/dev/null' # Silent pushd (error messages appear on stderr).
